#!/bin/bash

read -p "The name of the command you want to delete from the Termux command you created: > Name: " cmd_name

# Kiểm tra và xoá lệnh
if [[ -f ~/bin/$cmd_name ]]; then
    rm ~/bin/$cmd_name
    echo "Command '$cmd_name' deleted successfully!"
else
    echo "Command '$cmd_name' not found!"
fi
